- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: False
      tags:
      - install
  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
      - install
      - ssh
    - include_tasks: tasks/basic-setup.yml
      tags:
      - install
      - basic
    - include_tasks: tasks/git.yml
      tags:
      - install
      - git
    - include_tasks: tasks/docker.yml
      tags:
      - install
      - docker
    - include_tasks: tasks/spotify.yml
      tags:
      - install
      - spotify
    - include_tasks: tasks/zsh.yml
      tags:
      - install
      - zsh
    - include_tasks: tasks/brave.yml
      tags:
      - install
      - brave
    - include_tasks: tasks/slack.yml
      tags:
      - install
      - slack
    - include_tasks: tasks/dotfiles.yml
      tags:
      - install
      - dotfiles
