- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      tags:
      - install
  tasks:
    - include_tasks: tasks/docker.yml
      tags:
      - install
      - docker
    - include_tasks: tasks/spotify.yml
      tags:
      - install
      - spotify
    - include_tasks: tasks/zsh.yml
      tags:
      - install
      - zsh
    - include_tasks: tasks/brave.yml
      tags:
      - install
      - brave
