- name: Install System Packages
  become: true
  apt:
    name: ["curl", "i3"]
  tags:
    - install
    - basic

- name: Install Python
  become: true
  apt:
    name: ["python3-venv", "jupyter-notebook"]
  tags:
    - install
    - basic

- name: Install Golang
  become: true
  shell: curl -OL https://go.dev/dl/go1.19.4.linux-amd64.tar.gz && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
  tags:
    - install
    - basic

- name: Update /etc/profile
  lineinfile:
    dest: /etc/profile
    line: 'PATH=$PATH:/usr/local/go/bin'
  tags:
    - install
    - basic
