- name: Install System Packages
  become: true
  apt:
    name: ["curl", "git", "ca-certificates", "gnupg", "lsb-release", "nvidia-driver-515", "nvidia-dkms-515"]
  tags:
    - install
    - basic

- name: Install Python
  become: true
  apt:
    name: ["python3-venv", "jupyter-notebook"]
  tags:
    - install
    - basic
