- name: Add Spotify GPG apt Key
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present
  tags:
    - spotify
    - install

- name: Add Spotify Repository
  become: true
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
  tags:
    - spotify
    - install

- name: Spotify apt installation
  become: true
  apt: name=spotify-client
  tags:
    - spotify
    - install
