- name: Add Spotify GPG apt Key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present
  tags:
    - spotify
    - install
- name: Add Spotify Repository
  apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
  tags:
    - spotify
    - install
- name: Spotify apt installation
  become: true
  apt:
    update_cache: yes
    name: spotify-client
  tags:
    - spotify
    - install
